[project]
name = "workshoplib"
version = "0.1.0"
description = "Shared utilities and scripts for the NSBE PDC 2025 Python Workshop"
requires-python = ">=3.11"
dependencies = []

[build-system]
requires = ["uv_build>=0.8.13,<0.9.0"]
build-backend = "uv_build"
